apiVersion: content.hauler.cattle.io/v1
kind: Files
metadata:
  name: rancher-airgap-files-k3s
spec:
  files:
    # Installation scripts
    - path: https://raw.githubusercontent.com/k3s-io/k3s/refs/heads/release-1.33/install.sh
      name: install.sh
    # Linux AMD64
    - path: https://github.com/k3s-io/k3s/releases/download/v1.33.5%2Bk3s1/k3s
      name: k3s
    - path: https://github.com/k3s-io/k3s/releases/download/v1.33.5%2Bk3s1/k3s-airgap-images-amd64.tar.zst
      name: k3s-airgap-images-amd64.tar.zst
    - path: https://github.com/k3s-io/k3s/releases/download/v1.33.5%2Bk3s1/sha256sum-amd64.txt
      name: sha256sum-amd64.txt
    # Linux ARM64
    - path: https://github.com/k3s-io/k3s/releases/download/v1.33.5%2Bk3s1/k3s-airgap-images-arm64.tar.zst
      name: k3s-airgap-images-arm64.tar.zst
    - path: https://github.com/k3s-io/k3s/releases/download/v1.33.5%2Bk3s1/sha256sum-arm64.txt
      name: sha256sum-arm64.txt
    - path: https://github.com/k3s-io/k3s/releases/download/v1.33.5%2Bk3s1/k3s-arm64
      name: k3s-arm64
    # SELinux RPMs for Linux
    - path: https://github.com/k3s-io/k3s-selinux/releases/download/v1.6.latest.1/k3s-selinux-1.6-1.el9.noarch.rpm
      name: k3s-selinux-1.6-1.el9.noarch.rpm
    - path: https://github.com/k3s-io/k3s-selinux/releases/download/v1.6.latest.1/k3s-selinux-1.6-1.el9.noarch.rpm
      name: k3s-selinux-1.6-1.el8.noarch.rpm
    - path: https://github.com/k3s-io/k3s-selinux/releases/download/v1.6.latest.1/k3s-selinux-1.6-1.el9.noarch.rpm
      name: k3s-selinux-1.6-1.el7.noarch.rpm
    # Windows AMD64 (K3s does not have native Windows support - this would be for WSL2)
    # Note: K3s runs in WSL2 on Windows, using the Linux binary
    # macOS ARM64 (K3s runs in containers/VMs on macOS)
    # Note: K3s doesn't have native macOS binaries - runs via Docker Desktop/Rancher Desktop
    # Rancher Desktop for macOS ARM64
    - path: https://github.com/rancher-sandbox/rancher-desktop/releases/download/v1.20.1/Rancher.Desktop-1.20.1.aarch64.dmg
      name: rancher-desktop-1.20.1-mac.dmg
    # To configure Rancher Desktop to use Hauler registry for K3s images, see macOS setup instructions.
---
apiVersion: content.hauler.cattle.io/v1
kind: Images
metadata:
  name: rancher-airgap-images-k3s
spec:
  images:
    - name: rancher/klipper-helm:v0.9.8-build20250709
    - name: rancher/klipper-lb:v0.4.13
    - name: rancher/local-path-provisioner:v0.0.31
    - name: rancher/mirrored-coredns-coredns:1.12.3
    - name: rancher/mirrored-library-busybox:1.36.1
    - name: rancher/mirrored-library-traefik:3.3.6
    - name: rancher/mirrored-metrics-server:v0.8.0
    - name: rancher/mirrored-pause:3.6
